#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
HOSTNAME = '127.0.0.1'
IN_PORT = 8888
OUT_PORT = 8889
#
TILESIZE = 40
PLAYERSPEED = 40

BALLSPEED = 60
BALLLIFETIME = 10
BALLRADIUS = 40
#
TILESDIR = 'images/'
BLOCKTILES = ['stone', 'forest']
TRANSTILES = ['water']
ANIMATED_TILES = [] #['player']
#
ROUND_TIMER = 0.1
SERVER_TIMER = 0.1

PROFILE_CLIENT = 0
PROFILE_SERVER = 0

